//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchestratorService.ProxyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyService.IProxyService")]
    public interface IProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetContractNameFromCity", ReplyAction="http://tempuri.org/IProxyService/GetContractNameFromCityResponse")]
        string GetContractNameFromCity(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetContractNameFromCity", ReplyAction="http://tempuri.org/IProxyService/GetContractNameFromCityResponse")]
        System.Threading.Tasks.Task<string> GetContractNameFromCityAsync(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsJson", ReplyAction="http://tempuri.org/IProxyService/GetStationsJsonResponse")]
        string GetStationsJson(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsJson", ReplyAction="http://tempuri.org/IProxyService/GetStationsJsonResponse")]
        System.Threading.Tasks.Task<string> GetStationsJsonAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyServiceChannel : OrchestratorService.ProxyService.IProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceClient : System.ServiceModel.ClientBase<OrchestratorService.ProxyService.IProxyService>, OrchestratorService.ProxyService.IProxyService {
        
        public ProxyServiceClient() {
        }
        
        public ProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetContractNameFromCity(string cityName) {
            return base.Channel.GetContractNameFromCity(cityName);
        }
        
        public System.Threading.Tasks.Task<string> GetContractNameFromCityAsync(string cityName) {
            return base.Channel.GetContractNameFromCityAsync(cityName);
        }
        
        public string GetStationsJson(string contractName) {
            return base.Channel.GetStationsJson(contractName);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsJsonAsync(string contractName) {
            return base.Channel.GetStationsJsonAsync(contractName);
        }
    }
}
